### ISSUE TITLE
Duration parameter has no effect

### ISSUE THREAD

**Issue by ddejohn** [maxhumber/gif#12]
Different `gif.save()` parameters seem to have no effect.

Code to reproduce (`gif.save()` call on line 118): https://gist.github.com/ddejohn/fa67039541bdb7e387c403fe32a65eb9

## Different parameters, same gif produced

Here's an [album of gifs](https://imgur.com/a/Ho1xWNj) produced with four different sets of parameters:

```python
duration=100, unit="ms", between="frames"
duration=5, unit="ms", between="frames"
duration=1, unit="s", between="startend"
duration=10, unit="s", between="startend"
```

The only apparent difference is file size:

![](https://i.imgur.com/AkrUWiJ.png)

**Comment by ddejohn** [comment]
Hi, why was this issue closed with no response?

**Comment by maxhumber** [comment]
Unable to reproduce (with several new unit tests added).

**Comment by maxhumber** [comment]
See: https://github.com/maxhumber/gif/blob/master/tests/test_gif_matplotlib.py#L60

**Comment by kkoetter** [comment]
I encountered the same effect when running the sample code.
