### ISSUE TITLE
Consider using an image object

### ISSUE THREAD

**Issue by Stannislav** [maxhumber/gif#6]
Currently things happend in the global namespace. I think it would be very nice to be able to have separate objects for separate gifs, something like this:
```python
my_gif = GifObj()

@my_gif.frame
def frame(i):
  ...

my_gif.save_img("my_gif.gif", frames=range(100))
```

I can try to draft a PR if you want.

**Comment by maxhumber** [comment]
Hey @Stannislav, 

I initially had the same idea! But decided against it as I didn't think the library would gain that much for the additional effort.

I could be convinced otherwise, though...
