### ISSUE TITLE
Compatibility with plotly

### ISSUE THREAD

**Issue by alanrivetta** [maxhumber/gif#7]
Good day. Very useful this library!

I do not know how it works internally, however I would like to know if there is a way to use it (and if possible, in what way) with the plotly.py library

Thank you, have a nice day.

**Comment by maxhumber** [comment]
Hi @alanrivetta.

Thanks for the suggestion. I'm not super familiar with plotly... I'll see if I can whip something up in the next few weeks and integrate it into the package.

**Comment by maxhumber** [comment]
@alanrivetta Christmas came early ;)

https://github.com/maxhumber/gif/releases/tag/v3.0.0

You owe me an example for my gallery now!
